version: 2

sources:
  - name: raw
    schema: gz_raw_data  # où se situe la table dans BQ
    description: greenwez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales  # nom exact de la table dans BQ
        description: sales of greenweez / we have one row per product_id found in each order_id
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
        

      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique

      - name: ship
        identifier: raw_gz_ship
        description: Unique identifier for each shipping record / ship_cost by orders_id
        columns:
          - name: "(orders_id || '-' || orders_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: Impressions by campaign with adwords
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      
      - name: bing
        identifier: raw_gz_bing
        description: Impressions by campaign with bing 
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: criteo
        identifier: raw_gz_criteo
        description: Impressions by campaign with criteo 
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: facebook
        identifier: raw_gz_facebook
        description: Impressions by campaign with facebook
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null

models:    
  - name: int_campaigns
    description: Impressions by campaign for all paid media sources (fb, criteo, adwords, bing) 
    columns:
      - name: "(date_date || '-' || paid_source || '-' || campaign_key)"
        description: primary key of the table
        tests:
          - unique
          - not_null

  - name: int_campaigns_day
    description: Impressions by campaign for all paid media sources by day (fb, criteo, adwords, bing) 
    columns:
      - name: "(date_date || '-' || paid_source || '-' || campaign_key)"
        description: primary key of the table
        tests:
          - unique
          - not_null

